---
version: "3.7"
services:

  # ---------------------------------------------------------------------
  # | Nginx-Service                                                     |
  # ---------------------------------------------------------------------
  nginx-app:
    build:
      context: ../backend/static-app
      dockerfile: static-app.Dockerfile
    container_name: static-app
    restart: unless-stopped
    volumes:
      - ../frontend/static-app/dist:/usr/share/nginx/html
    labels:
      - traefik.enable=true
      # Routers
      - traefik.http.routers.static-app.entrypoints=web
      - traefik.http.routers.static-app.middlewares=test-redirectscheme
      - traefik.http.routers.static-app-secure.entrypoints=websecure
      - traefik.http.routers.static-app-secure.tls.certresolver=myresolver
      - traefik.http.routers.static-app-secure.tls=true
      - traefik.http.routers.static-app-secure.middlewares=test-compress,test-redirectscheme
      # Services
      - traefik.http.services.static-app-secure.loadbalancer.server.port=80
      # Middlewares
      - traefik.http.middlewares.test-compress.compress=true
      - traefik.http.middlewares.test-redirectscheme.redirectscheme.scheme=https
      - traefik.http.middlewares.test-redirectscheme.redirectscheme.permanent=true
      - traefik.http.middlewares.test-redirectscheme.redirectscheme.port=443
